word_list={"Sports":["cricket","football","hockey","rugby","soccer","tennis","baseball","golf","running","badmintom","swimming","boxing",
"table tennis","skiing","ice skating","roller-skating","darts",
"snowboarding","hang gliding","bungee jumping","windsurfing"],
"Movies":["batman","avengers","jumanji","justice league","fast & furious","stuart little","the incredible hulk",
"white house down","ala vaikuntapuramuloo","bahubali","war","kgf","pogaru","robert","kotigobba", 
"avane sriman narayana", "bell bottom", "ondu motteya kate"],
"Video Games":["Fortnite","world of warcraft","pubg","free fire","grand theft auto v","counter strike""candy crush",
"among us","combat rifile","gta vice city","tennis","hill climb racing","temple run", 
"moto gp","valorant","prince of persia","assassin creed","road rash", 
"far cry","claw","tetris","solraite"],
"Diseases":["acne","corona","fever","malaria","cough","cancer","alergies",
"asthma","brain tumor","bronchitis","coma","croup","diabetes","diarrheoa", 
"depression","earache","epilepsy","flu","fibroids","gout","gum disease", 
"haemorrhoids","nosebleed","measles","hiv","toothache"],
"Countries":["india","unitedkingdom","sydney","germany","russia","bhutan", 
"singapore","malaysia","egypt","capetown","united states", 
"portugal","brazil","canada","marryland","denmark","norway","switzerland",
"afghanistan","srilanka","nepal","turkey","sudan","southafrica","mali","morocco","argentina","greenland",
"romania","spain","philippines","new zealand","papua new guinea","south korea","japan","mongolia","finland"]}